config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/about'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_Name, :last_Name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form|%>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex flex-col gap-3 justify-center bg-blue-400 rounded-xl shadow-lg shadow-pink-600">
    <div class="flex flex-row justify-around p-3">
      <%= form.label :first_name, class: "text-xl font-bold" %>
      <%= form.text_field :first_name, class: "border border-black hover:border-2 p-2 hover:border-pink-300 rounded-xl", placeholder: "First Name" %>
    </div>

    <div class="flex flex-row justify-around">
      <%= form.label :last_name, class: "text-xl font-bold" %>
      <%= form.text_field :last_name, class: "border border-black hover:border-2 hover:border-pink-300 p-2 rounded-xl", placeholder: "Last Name"  %>
    </div>

    <div class="flex flex-row justify-around">
      <%= form.label :email, class: "text-xl font-bold" %>
      <%= form.text_field :email, class: "border border-black hover:border-2 hover:border-pink-300 p-2 rounded-xl", placeholder: "Email"  %>
    </div>

    <div class="flex flex-row justify-around">
      <%= form.label :phone, class: "text-xl font-bold" %>
      <%= form.text_field :phone, class: "border border-black hover:border-2 hover:border-pink-300 p-2 rounded-xl", placeholder: "Phone"  %>
    </div>

    <div class="flex flex-row justify-around">
      <%= form.label :twitter, class: "text-xl font-bold" %>
      <%= form.text_field :twitter, class: "border border-black hover:border-2 hover:border-pink-300 p-2 rounded-xl", placeholder: "Twitter"  %>
    </div>

    <div class="m-4 flex flex-row justify-center  cursor-pointer text-2xl px-2 py-4 rounded-xl bg-pink-400 text-white">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>" class="text-white text-lg md:text-4xl">
  <p>
    <strong>First name:</strong>
    <%= friend.first_Name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_Name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<!-- Apply green color to the notice message -->
<p class="text-green-500"><%= notice %></p>
<div class="flex flex-col bg-pink-400 shadow-xl shadow-blue-800 rounded-xl">
<h1 class="text-4xl text-white font-bold text-center p-4 font-bold">Friends</h1>

<div id="friends">
  <% @friends.each do |friend| %>
    <!-- Add a div container for each friend with flexbox styling -->
    <div class="friend-container text-3xl p-4 flex bg-blue-400 m-3 flex-row gap-3 flex-wrap border-2 border-green-500 rounded-xl">
      <%= render friend %>
    </div>
    <p>
      <!-- Create a link to show the friend's details with pink background and white text -->
      <%= link_to "Show this friend", friend, class: "text-center m-4 rounded-xl text-xl md:text-3xl px-4 py-2 bg-pink-600 text-white" %>
    </p>
  <% end %>
</div>

<!-- Add a link to create a new friend -->
<%= link_to "New friend", new_friend_path, class: "text-center flex justify-center items-center m-6 rounded-xl text-xl md:text-3xl px-4 py-2 bg-pink-600 text-white"  %>
</div>

app/views/friends/new.html.erb
<div class="bg-blue-300 flex flex-col p-4 rounded-xl shadow-xl shadow-blue-800">
<h1 class="text-pink-400 p-3 text-4xl font-bold font-strong">New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div class="text-center">
  <%= link_to "Back to friends", friends_path %>
</div>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="bg-blue-400 p-3  rounded-xl shadow-pink-400">
<%= render @friend %>

<div class="shadow-pink-400 shadow-xl text-2xl p-3 text-white flex flex-col md:flex-row gap-3 justify-center items-center">
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"px-4 py-2 m-3 bg-pink-500 rounded-xl shadow-xl shadow-blue-800" %> 
  <%= link_to "Back to friends", friends_path,class:"px-4 py-2 m-3 bg-pink-500 rounded-xl shadow-xl shadow-blue-800"  %>

  <%= button_to "Destroy this friend", @friend, method: :delete,class:"px-4 py-2 m-3 bg-pink-500 rounded-xl shadow-xl shadow-blue-800"   %>
</div>
</div>

app/views/home/_header.html.erb
<nav class="bg-blue-500 shadow-xl shadow-blue-800 rounded-b-xl p-8 flex flex-row justify-between">
    <div class="flex flex-row gap-5">
        <%= link_to 'Friend App', root_path, class: "text-4xl font-bold text-pink-400" %>
        <%= link_to 'About Us', home_about_path, class: "text-2xl text-pink-400" %>
        <%= link_to 'Friends', friends_path, class: "text-2xl text-pink-400" %>
        
           <% if user_signed_in? %>
        <li class="text-2xl text-pink-400">
          <%= link_to "Add Friend", new_friend_path, class:"text-2xl text-pink-400" %>
        </li>

        <li class="text-2xl text-pink-400">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"text-2xl text-pink-400" %>
        </li>

        <li class="text-2xl text-pink-400">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"text-2xl text-pink-400" %>
        </li>

    <% else %>
        <li class="text-2xl text-pink-400">
            <%= link_to "Sign Up", new_user_registration_path, class:"text-2xl text-pink-400" %>
        </li>

        <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"text-2xl text-pink-400" %>
        </li>
    <% end %>               
    </div> 
    <div class="flex flex-row gap-3">
        <input type="text" placeholder="Search.." class="rounded-xl p-3 border border-2 border-blue-200 hover:border-2 hover:border-blue-700"/>
        <button class="text-white border-blue-800 border-2 rounded-xl p-3 text-2xl font-bold hover:bg-pink-400">Search</button>
    </div>
</nav>

app/views/home/about.html.erb
<h1 class="text-6xl p-6 font-bold text-green-600">About page..</h1>

app/views/home/index.html.erb
<h1 class="text-2xl font-bold p-4">Hello World</h1>
<p>This is my first Rails Webpage</p>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
      <title>Friends</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <%= render 'home/header' %>
  <div class="p-8">
  <%= yield %>
  </div>
</body>
</html>